"""
Django settings for puntoexeconfig project.
Generated by 'django-admin startproject' using Django 4.1.4.
For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
import sentry_sdk
from pathlib import Path
from django.contrib.messages import constants as messages
from dotenv import load_dotenv
from sentry_sdk.integrations.django import DjangoIntegration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)+(zx+xn)c^zcb+_#gnpa6ii7whzlj$k4%i6davhs5rb8)gh#y'

# SECURITY WARNING: don't run with debug turned on in production!
if os.getenv('DJANGO_ENV') in ["prod", "qas"]:
    DEBUG = False
    USE_X_FORWARDED_HOST = True
    ALLOWED_HOSTS = [".tecnoglass.net"]
else:
    DEBUG = True
    ALLOWED_HOSTS = ['*']
    #llamar al archivo .env para configurar la variable de entorno de desarrollo
    load_dotenv()


# Application definition
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'auditlog',
    'widget_tweaks',
    'apps.pages',
    'apps.users',
    'apps.productos',
    'apps.pedidos',
    'apps.inventario',
    # 3rd Party
    'rest_framework',
    'django_filters',
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
]

ROOT_URLCONF = 'puntoexeconfig.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        # 'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
if DEBUG:
    TEMPLATES[0]["OPTIONS"]["loaders"] = ['django.template.loaders.filesystem.Loader', 'django.template.loaders.app_directories.Loader']

WSGI_APPLICATION = 'puntoexeconfig.wsgi.application'

AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']

AUTH_USER_MODEL = 'users.CustomUser'

AUDITLOG_INCLUDE_ALL_MODELS=True

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
if os.getenv('DJANGO_ENV') == "prod":
     DATABASES = {
        "default": {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'postgres',
            'USER': 'postgres',
            'PASSWORD': '2QkD7!riKh-$cDQ',
            'HOST': 'db.esczdnbbfghqdniccxzv.supabase.co',
            'PORT': '5432'
        }
    }
if os.getenv('DJANGO_ENV') == "qas":
    pass
if os.getenv('DJANGO_ENV') == "dev":

    DATABASES = {
        "default": {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'postgres',
            'USER': 'postgres',
            'PASSWORD': '2QkD7!riKh-$cDQ',
            'HOST': 'db.esczdnbbfghqdniccxzv.supabase.co',
            'PORT': '5432'
        }
    }




AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



MESSAGE_TAGS = {
    messages.ERROR: 'danger'
}

# LOGIN_URL = 'login'

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
STATIC_URL = 'static/'

if os.getenv('DJANGO_ENV') in ('dev', 'qas', 'prod'):
    STATIC_ROOT = 'static_root/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / "media_root"

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
RECAPTCHA_SECRET_KEY = "6LfBhbYbAAAAAD5i59wwXuq_3oaH2zZdNfer06OR"
